# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/test20220916',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/test20220916',
                'lib_path': 'test20220916'},
  'syms': {'test20220916.core': {'test20220916.core.foo': ('core.html#foo', 'test20220916/core.py')}}}